"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express = require("express");
const feed_1 = require("./feed");
const entry_1 = require("./entry");
const category_1 = require("./category");
exports.router = express.Router();
exports.router.use("/feed", feed_1.feedRoute);
exports.router.use("/entry", entry_1.entryRoute);
exports.router.use("/category", category_1.categoryRoute);
